# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TSAnalyzer/TSWidgets/analysis_batch.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(860, 694)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_2.setSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label.setObjectName("label")
        self.horizontalLayout_22.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem)
        self.selectButton = QtWidgets.QPushButton(Dialog)
        self.selectButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.selectButton.setObjectName("selectButton")
        self.horizontalLayout_22.addWidget(self.selectButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_7.addWidget(self.listWidget)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.countLabel = QtWidgets.QLabel(Dialog)
        self.countLabel.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.countLabel.setObjectName("countLabel")
        self.horizontalLayout_15.addWidget(self.countLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.deleteButton = QtWidgets.QPushButton(Dialog)
        self.deleteButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout_15.addWidget(self.deleteButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.dockWidget = QtWidgets.QDockWidget(Dialog)
        self.dockWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.consoleEdit = QtWidgets.QPlainTextEdit(self.dockWidgetContents)
        self.consoleEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.consoleEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.consoleEdit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.consoleEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.consoleEdit.setReadOnly(True)
        self.consoleEdit.setObjectName("consoleEdit")
        self.gridLayout_6.addWidget(self.consoleEdit, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.gridLayout_2.addWidget(self.dockWidget, 1, 0, 1, 2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.offsetEdit = QtWidgets.QLineEdit(Dialog)
        self.offsetEdit.setEnabled(True)
        self.offsetEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.offsetEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.offsetEdit.setReadOnly(True)
        self.offsetEdit.setObjectName("offsetEdit")
        self.horizontalLayout.addWidget(self.offsetEdit)
        self.offsetButton = QtWidgets.QToolButton(Dialog)
        self.offsetButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.offsetButton.setText("")
        self.offsetButton.setObjectName("offsetButton")
        self.horizontalLayout.addWidget(self.offsetButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.outlierGroup = QtWidgets.QGroupBox(Dialog)
        self.outlierGroup.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.outlierGroup.setFlat(False)
        self.outlierGroup.setCheckable(True)
        self.outlierGroup.setObjectName("outlierGroup")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.outlierGroup)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.outlierGroup)
        self.label_7.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.iqrWindowBox = QtWidgets.QSpinBox(self.outlierGroup)
        self.iqrWindowBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.iqrWindowBox.setMaximum(9999)
        self.iqrWindowBox.setProperty("value", 365)
        self.iqrWindowBox.setObjectName("iqrWindowBox")
        self.horizontalLayout_8.addWidget(self.iqrWindowBox)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.outlierGroup)
        self.label_5.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.sigmaEdit = QtWidgets.QLineEdit(self.outlierGroup)
        self.sigmaEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.sigmaEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.sigmaEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sigmaEdit.setInputMask("")
        self.sigmaEdit.setObjectName("sigmaEdit")
        self.horizontalLayout_6.addWidget(self.sigmaEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_19 = QtWidgets.QLabel(self.outlierGroup)
        self.label_19.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.outlierDirEdit = QtWidgets.QLineEdit(self.outlierGroup)
        self.outlierDirEdit.setEnabled(True)
        self.outlierDirEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.outlierDirEdit.setReadOnly(True)
        self.outlierDirEdit.setObjectName("outlierDirEdit")
        self.horizontalLayout_4.addWidget(self.outlierDirEdit)
        self.outlierDirButton = QtWidgets.QToolButton(self.outlierGroup)
        self.outlierDirButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.outlierDirButton.setText("")
        self.outlierDirButton.setObjectName("outlierDirButton")
        self.horizontalLayout_4.addWidget(self.outlierDirButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.outlierGroup)
        self.label_6.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.iqrBox = QtWidgets.QSpinBox(self.outlierGroup)
        self.iqrBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.iqrBox.setMaximum(5)
        self.iqrBox.setProperty("value", 1)
        self.iqrBox.setObjectName("iqrBox")
        self.horizontalLayout_7.addWidget(self.iqrBox)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_20 = QtWidgets.QLabel(self.outlierGroup)
        self.label_20.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_19.addWidget(self.label_20)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem5)
        self.outlierNameEdit = QtWidgets.QLineEdit(self.outlierGroup)
        self.outlierNameEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.outlierNameEdit.setObjectName("outlierNameEdit")
        self.horizontalLayout_19.addWidget(self.outlierNameEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_19, 4, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.outlierGroup)
        self.analysisGroup = QtWidgets.QGroupBox(Dialog)
        self.analysisGroup.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.analysisGroup.setCheckable(True)
        self.analysisGroup.setObjectName("analysisGroup")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.analysisGroup)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_8 = QtWidgets.QLabel(self.analysisGroup)
        self.label_8.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_24.addWidget(self.label_8)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem6)
        self.polyBox = QtWidgets.QSpinBox(self.analysisGroup)
        self.polyBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.polyBox.setProperty("value", 1)
        self.polyBox.setObjectName("polyBox")
        self.horizontalLayout_24.addWidget(self.polyBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_9 = QtWidgets.QLabel(self.analysisGroup)
        self.label_9.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_25.addWidget(self.label_9)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem7)
        self.periodEdit = QtWidgets.QLineEdit(self.analysisGroup)
        self.periodEdit.setEnabled(True)
        self.periodEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.periodEdit.setObjectName("periodEdit")
        self.horizontalLayout_25.addWidget(self.periodEdit)
        self.verticalLayout_9.addLayout(self.horizontalLayout_25)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.analysisGroup)
        self.label_10.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.logDirEdit = QtWidgets.QLineEdit(self.analysisGroup)
        self.logDirEdit.setEnabled(True)
        self.logDirEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.logDirEdit.setReadOnly(True)
        self.logDirEdit.setObjectName("logDirEdit")
        self.horizontalLayout_5.addWidget(self.logDirEdit)
        self.logDirButton = QtWidgets.QToolButton(self.analysisGroup)
        self.logDirButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.logDirButton.setText("")
        self.logDirButton.setObjectName("logDirButton")
        self.horizontalLayout_5.addWidget(self.logDirButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_9.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.analysisGroup)
        self.label_11.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.saveDirEdit = QtWidgets.QLineEdit(self.analysisGroup)
        self.saveDirEdit.setEnabled(True)
        self.saveDirEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.saveDirEdit.setReadOnly(True)
        self.saveDirEdit.setObjectName("saveDirEdit")
        self.horizontalLayout_9.addWidget(self.saveDirEdit)
        self.saveDirButton = QtWidgets.QToolButton(self.analysisGroup)
        self.saveDirButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.saveDirButton.setText("")
        self.saveDirButton.setObjectName("saveDirButton")
        self.horizontalLayout_9.addWidget(self.saveDirButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.verticalLayout_9.addLayout(self.verticalLayout_4)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_14 = QtWidgets.QLabel(self.analysisGroup)
        self.label_14.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_10.addWidget(self.label_14)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.saveNameEdit = QtWidgets.QLineEdit(self.analysisGroup)
        self.saveNameEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.saveNameEdit.setObjectName("saveNameEdit")
        self.horizontalLayout_10.addWidget(self.saveNameEdit)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.verticalLayout_5.addWidget(self.analysisGroup)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.timeGroup = QtWidgets.QGroupBox(Dialog)
        self.timeGroup.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.timeGroup.setCheckable(True)
        self.timeGroup.setObjectName("timeGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.timeGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.timeEdit = QtWidgets.QPlainTextEdit(self.timeGroup)
        self.timeEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.timeEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout.addWidget(self.timeEdit, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.timeGroup)
        self.stackingGroup = QtWidgets.QGroupBox(Dialog)
        self.stackingGroup.setEnabled(False)
        self.stackingGroup.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.stackingGroup.setCheckable(True)
        self.stackingGroup.setObjectName("stackingGroup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.stackingGroup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.stackingGroup)
        self.label_4.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.cmeBox = QtWidgets.QComboBox(self.stackingGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmeBox.sizePolicy().hasHeightForWidth())
        self.cmeBox.setSizePolicy(sizePolicy)
        self.cmeBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cmeBox.setObjectName("cmeBox")
        self.cmeBox.addItem("")
        self.cmeBox.addItem("")
        self.horizontalLayout_3.addWidget(self.cmeBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.stackingGroup)
        self.label_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cmeEdit = QtWidgets.QLineEdit(self.stackingGroup)
        self.cmeEdit.setEnabled(False)
        self.cmeEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cmeEdit.setReadOnly(True)
        self.cmeEdit.setObjectName("cmeEdit")
        self.horizontalLayout_2.addWidget(self.cmeEdit)
        self.cmeButton = QtWidgets.QToolButton(self.stackingGroup)
        self.cmeButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cmeButton.setText("")
        self.cmeButton.setObjectName("cmeButton")
        self.horizontalLayout_2.addWidget(self.cmeButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.stackingGroup)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_23.addWidget(self.label_24)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_23.addWidget(self.progressBar)
        self.batchButton = QtWidgets.QPushButton(Dialog)
        self.batchButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.batchButton.setObjectName("batchButton")
        self.horizontalLayout_23.addWidget(self.batchButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_23)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "TSAnalyzer Detrend"))
        self.label.setText(_translate("Dialog", "Time Serie Files"))
        self.selectButton.setText(_translate("Dialog", "Add"))
        self.listWidget.setSortingEnabled(True)
        self.countLabel.setText(_translate("Dialog", "Total: 0"))
        self.deleteButton.setText(_translate("Dialog", "Delete"))
        self.dockWidget.setWindowTitle(_translate("Dialog", "Console"))
        self.label_2.setText(_translate("Dialog", "Offsets File"))
        self.outlierGroup.setTitle(_translate("Dialog", "Outlier"))
        self.label_7.setText(_translate("Dialog", "Window"))
        self.label_5.setText(_translate("Dialog", "Sigma"))
        self.sigmaEdit.setText(_translate("Dialog", "30 30 30"))
        self.label_19.setText(_translate("Dialog", "Save Dir"))
        self.outlierDirEdit.setText(_translate("Dialog", "clean"))
        self.label_6.setText(_translate("Dialog", "IQR Factor"))
        self.label_20.setText(_translate("Dialog", "Data Name Suffix"))
        self.outlierNameEdit.setText(_translate("Dialog", "clean"))
        self.analysisGroup.setTitle(_translate("Dialog", "Analysis"))
        self.label_8.setText(_translate("Dialog", "Polynomials"))
        self.label_9.setText(_translate("Dialog", "Periods"))
        self.periodEdit.setText(_translate("Dialog", "0.5 1"))
        self.label_10.setText(_translate("Dialog", "Log Dir"))
        self.logDirEdit.setText(_translate("Dialog", "log"))
        self.label_11.setText(_translate("Dialog", "Save Dir"))
        self.saveDirEdit.setText(_translate("Dialog", "residual"))
        self.label_14.setText(_translate("Dialog", "Data Name Suffix"))
        self.saveNameEdit.setText(_translate("Dialog", "residual"))
        self.timeGroup.setTitle(_translate("Dialog", "Time Interval"))
        self.timeEdit.setPlainText(_translate("Dialog", "# # stands for comment\n"
"# The first line if suit for whole time series file\n"
"# space between from start and end time\n"
"# format should be ymd(hms) can be omitted\n"
"20000101 20140101\n"
"# 200001011200 201401011200\n"
"# The following lines should be in the format\n"
"# site omit_start omit_end\n"
"tain 20000101 20140101"))
        self.stackingGroup.setTitle(_translate("Dialog", "Regional Filtering"))
        self.label_4.setText(_translate("Dialog", "Method"))
        self.cmeBox.setItemText(0, _translate("Dialog", "Stacking"))
        self.cmeBox.setItemText(1, _translate("Dialog", "PCA"))
        self.label_3.setText(_translate("Dialog", "Common Mode Errors"))
        self.label_24.setText(_translate("Dialog", "Progress"))
        self.batchButton.setText(_translate("Dialog", "Batch"))

