# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TSAnalyzer/TSWidgets/date.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(323, 218)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dateRadio = QtWidgets.QRadioButton(self.groupBox)
        self.dateRadio.setText("")
        self.dateRadio.setChecked(True)
        self.dateRadio.setObjectName("dateRadio")
        self.horizontalLayout.addWidget(self.dateRadio)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.dateEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.dateEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setTime(QtCore.QTime(0, 0, 0))
        self.dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1975, 9, 14), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout.addWidget(self.dateEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mjdRadio = QtWidgets.QRadioButton(self.groupBox)
        self.mjdRadio.setText("")
        self.mjdRadio.setChecked(False)
        self.mjdRadio.setObjectName("mjdRadio")
        self.horizontalLayout_2.addWidget(self.mjdRadio)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.mjdEdit = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.mjdEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.mjdEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.mjdEdit.setDecimals(1)
        self.mjdEdit.setMaximum(99999.9)
        self.mjdEdit.setObjectName("mjdEdit")
        self.horizontalLayout_2.addWidget(self.mjdEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.juldayRadio = QtWidgets.QRadioButton(self.groupBox)
        self.juldayRadio.setText("")
        self.juldayRadio.setObjectName("juldayRadio")
        self.horizontalLayout_3.addWidget(self.juldayRadio)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.juldayEdit = QtWidgets.QLineEdit(self.groupBox)
        self.juldayEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.juldayEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.juldayEdit.setObjectName("juldayEdit")
        self.horizontalLayout_3.addWidget(self.juldayEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.dyRadio = QtWidgets.QRadioButton(self.groupBox)
        self.dyRadio.setText("")
        self.dyRadio.setObjectName("dyRadio")
        self.horizontalLayout_4.addWidget(self.dyRadio)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.dyEdit = QtWidgets.QLineEdit(self.groupBox)
        self.dyEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.dyEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.dyEdit.setObjectName("dyEdit")
        self.horizontalLayout_4.addWidget(self.dyEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ydRadio = QtWidgets.QRadioButton(self.groupBox)
        self.ydRadio.setText("")
        self.ydRadio.setObjectName("ydRadio")
        self.horizontalLayout_5.addWidget(self.ydRadio)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.ydEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ydEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.ydEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.ydEdit.setObjectName("ydEdit")
        self.horizontalLayout_5.addWidget(self.ydEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gpsweekRadio = QtWidgets.QRadioButton(self.groupBox)
        self.gpsweekRadio.setText("")
        self.gpsweekRadio.setObjectName("gpsweekRadio")
        self.horizontalLayout_7.addWidget(self.gpsweekRadio)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.gpsweekEdit = QtWidgets.QLineEdit(self.groupBox)
        self.gpsweekEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.gpsweekEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.gpsweekEdit.setObjectName("gpsweekEdit")
        self.horizontalLayout_7.addWidget(self.gpsweekEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.conversionButton = QtWidgets.QPushButton(Dialog)
        self.conversionButton.setObjectName("conversionButton")
        self.horizontalLayout_6.addWidget(self.conversionButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.mjdEdit.editingFinished.connect(self.mjdRadio.click)
        self.juldayEdit.textEdited['QString'].connect(self.juldayRadio.click)
        self.dyEdit.textEdited['QString'].connect(self.dyRadio.click)
        self.ydEdit.textEdited['QString'].connect(self.ydRadio.click)
        self.dateEdit.editingFinished.connect(self.dateRadio.click)
        self.gpsweekEdit.textEdited['QString'].connect(self.gpsweekRadio.click)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Date Conversion Tools"))
        self.label.setText(_translate("Dialog", "Date"))
        self.dateEdit.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.label_3.setText(_translate("Dialog", "MJD"))
        self.label_2.setText(_translate("Dialog", "Julday"))
        self.juldayEdit.setText(_translate("Dialog", "2451545"))
        self.label_4.setText(_translate("Dialog", "Demical Year"))
        self.dyEdit.setText(_translate("Dialog", "2000.0000"))
        self.label_5.setText(_translate("Dialog", "Year Doy"))
        self.ydEdit.setText(_translate("Dialog", "2000-001"))
        self.label_6.setText(_translate("Dialog", "GPSWeek"))
        self.gpsweekEdit.setText(_translate("Dialog", "10426"))
        self.conversionButton.setText(_translate("Dialog", "Convert"))

