# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TSAnalyzer/TSWidgets/header.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(841, 553)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.addFilesButton = QtWidgets.QToolButton(Form)
        self.addFilesButton.setObjectName("addFilesButton")
        self.horizontalLayout_2.addWidget(self.addFilesButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.filesListWidget = QtWidgets.QListWidget(Form)
        self.filesListWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.filesListWidget.setObjectName("filesListWidget")
        self.verticalLayout_3.addWidget(self.filesListWidget)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(3, 3, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.deleteButton = QtWidgets.QPushButton(Form)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout_10.addWidget(self.deleteButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.previewEdit = QtWidgets.QPlainTextEdit(Form)
        self.previewEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.previewEdit.setObjectName("previewEdit")
        self.verticalLayout.addWidget(self.previewEdit)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(6, 6, -1, 6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.unitEdit = QtWidgets.QLineEdit(self.groupBox)
        self.unitEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.unitEdit.setObjectName("unitEdit")
        self.horizontalLayout_3.addWidget(self.unitEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.timeUnitBox = QtWidgets.QComboBox(self.groupBox)
        self.timeUnitBox.setObjectName("timeUnitBox")
        self.timeUnitBox.addItem("")
        self.timeUnitBox.addItem("")
        self.horizontalLayout_3.addWidget(self.timeUnitBox)
        spacerItem3 = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.scaleEdit = QtWidgets.QLineEdit(self.groupBox)
        self.scaleEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.scaleEdit.setInputMask("")
        self.scaleEdit.setObjectName("scaleEdit")
        self.horizontalLayout_3.addWidget(self.scaleEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.colIndexEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colIndexEdit.sizePolicy().hasHeightForWidth())
        self.colIndexEdit.setSizePolicy(sizePolicy)
        self.colIndexEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.colIndexEdit.setObjectName("colIndexEdit")
        self.verticalLayout_2.addWidget(self.colIndexEdit)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.colNameEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colNameEdit.sizePolicy().hasHeightForWidth())
        self.colNameEdit.setSizePolicy(sizePolicy)
        self.colNameEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.colNameEdit.setObjectName("colNameEdit")
        self.verticalLayout_4.addWidget(self.colNameEdit)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 2, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.indexColEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indexColEdit.sizePolicy().hasHeightForWidth())
        self.indexColEdit.setSizePolicy(sizePolicy)
        self.indexColEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.indexColEdit.setObjectName("indexColEdit")
        self.verticalLayout_5.addWidget(self.indexColEdit)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 3, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.indexFormatsEdit = QtWidgets.QLineEdit(self.groupBox)
        self.indexFormatsEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indexFormatsEdit.sizePolicy().hasHeightForWidth())
        self.indexFormatsEdit.setSizePolicy(sizePolicy)
        self.indexFormatsEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.indexFormatsEdit.setReadOnly(True)
        self.indexFormatsEdit.setObjectName("indexFormatsEdit")
        self.verticalLayout_6.addWidget(self.indexFormatsEdit)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 4, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.dirEdit = QtWidgets.QLineEdit(Form)
        self.dirEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.dirEdit.setReadOnly(True)
        self.dirEdit.setObjectName("dirEdit")
        self.horizontalLayout_5.addWidget(self.dirEdit)
        self.dirButton = QtWidgets.QToolButton(Form)
        self.dirButton.setText("")
        self.dirButton.setObjectName("dirButton")
        self.horizontalLayout_5.addWidget(self.dirButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.consoleLabel = QtWidgets.QLabel(Form)
        self.consoleLabel.setObjectName("consoleLabel")
        self.verticalLayout.addWidget(self.consoleLabel)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.writeButton = QtWidgets.QPushButton(Form)
        self.writeButton.setObjectName("writeButton")
        self.horizontalLayout.addWidget(self.writeButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Header Tool"))
        self.label.setText(_translate("Form", "Add Files"))
        self.addFilesButton.setText(_translate("Form", "..."))
        self.addFilesButton.setShortcut(_translate("Form", "Ctrl+O"))
        self.deleteButton.setText(_translate("Form", "Delete"))
        self.deleteButton.setShortcut(_translate("Form", "Ctrl+D"))
        self.label_5.setText(_translate("Form", "File Preview"))
        self.groupBox.setTitle(_translate("Form", "Header Comment"))
        self.label_4.setText(_translate("Form", "Unit"))
        self.unitEdit.setText(_translate("Form", "mm"))
        self.label_11.setText(_translate("Form", "Time Unit"))
        self.timeUnitBox.setItemText(0, _translate("Form", "years"))
        self.timeUnitBox.setItemText(1, _translate("Form", "days"))
        self.label_7.setText(_translate("Form", "Scale"))
        self.scaleEdit.setText(_translate("Form", "1"))
        self.label_6.setText(_translate("Form", "Column indexes"))
        self.label_9.setText(_translate("Form", "Column names"))
        self.label_8.setText(_translate("Form", "Index columns"))
        self.label_10.setText(_translate("Form", "Index formats"))
        self.label_3.setText(_translate("Form", "Directory"))
        self.consoleLabel.setText(_translate("Form", "TextLabel"))
        self.writeButton.setText(_translate("Form", "Write"))

