# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TSAnalyzer/TSWidgets/main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1344, 800)
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("DockWidget::title {\n"
"    font: bold;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setAutoFillBackground(True)
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget.addTab(self.tab2, "")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.analysisDock = QtWidgets.QDockWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analysisDock.sizePolicy().hasHeightForWidth())
        self.analysisDock.setSizePolicy(sizePolicy)
        self.analysisDock.setMinimumSize(QtCore.QSize(80, 209))
        self.analysisDock.setMaximumSize(QtCore.QSize(300, 524287))
        self.analysisDock.setObjectName("analysisDock")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_10.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.toolBox = QtWidgets.QToolBox(self.dockWidgetContents)
        self.toolBox.setStyleSheet("")
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolBox.setObjectName("toolBox")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 289, 464))
        self.page_3.setObjectName("page_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.diffButton = QtWidgets.QPushButton(self.page_3)
        self.diffButton.setObjectName("diffButton")
        self.horizontalLayout_18.addWidget(self.diffButton)
        spacerItem = QtWidgets.QSpacerItem(155, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem)
        self.cumsumButton = QtWidgets.QPushButton(self.page_3)
        self.cumsumButton.setObjectName("cumsumButton")
        self.horizontalLayout_18.addWidget(self.cumsumButton)
        spacerItem1 = QtWidgets.QSpacerItem(155, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_18)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.page_3)
        self.tabWidget_2.setMaximumSize(QtCore.QSize(271, 16777215))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tabWidgetPage1)
        self.verticalLayout_11.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_11.setSpacing(3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSpacing(3)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.msRadio = QtWidgets.QRadioButton(self.tabWidgetPage1)
        self.msRadio.setChecked(False)
        self.msRadio.setObjectName("msRadio")
        self.horizontalLayout_33.addWidget(self.msRadio)
        self.bzRadio = QtWidgets.QRadioButton(self.tabWidgetPage1)
        self.bzRadio.setChecked(True)
        self.bzRadio.setObjectName("bzRadio")
        self.horizontalLayout_33.addWidget(self.bzRadio)
        self.verticalLayout_14.addLayout(self.horizontalLayout_33)
        self.alphaWidget = QtWidgets.QWidget(self.tabWidgetPage1)
        self.alphaWidget.setObjectName("alphaWidget")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.alphaWidget)
        self.horizontalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_34.setSpacing(0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_23 = QtWidgets.QLabel(self.alphaWidget)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_34.addWidget(self.label_23)
        spacerItem2 = QtWidgets.QSpacerItem(153, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem2)
        self.alphaLineEdit = QtWidgets.QLineEdit(self.alphaWidget)
        self.alphaLineEdit.setObjectName("alphaLineEdit")
        self.horizontalLayout_34.addWidget(self.alphaLineEdit)
        self.verticalLayout_14.addWidget(self.alphaWidget)
        self.betaWidget = QtWidgets.QWidget(self.tabWidgetPage1)
        self.betaWidget.setObjectName("betaWidget")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.betaWidget)
        self.horizontalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_35.setSpacing(0)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_24 = QtWidgets.QLabel(self.betaWidget)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_35.addWidget(self.label_24)
        spacerItem3 = QtWidgets.QSpacerItem(156, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem3)
        self.betaLineEdit = QtWidgets.QLineEdit(self.betaWidget)
        self.betaLineEdit.setObjectName("betaLineEdit")
        self.horizontalLayout_35.addWidget(self.betaLineEdit)
        self.verticalLayout_14.addWidget(self.betaWidget)
        self.gammaWidget = QtWidgets.QWidget(self.tabWidgetPage1)
        self.gammaWidget.setObjectName("gammaWidget")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.gammaWidget)
        self.horizontalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_36.setSpacing(0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_25 = QtWidgets.QLabel(self.gammaWidget)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_36.addWidget(self.label_25)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem4)
        self.gammaLineEdit = QtWidgets.QLineEdit(self.gammaWidget)
        self.gammaLineEdit.setObjectName("gammaLineEdit")
        self.horizontalLayout_36.addWidget(self.gammaLineEdit)
        self.verticalLayout_14.addWidget(self.gammaWidget)
        self.widget = QtWidgets.QWidget(self.tabWidgetPage1)
        self.widget.setObjectName("widget")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_20 = QtWidgets.QLabel(self.widget)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_27.addWidget(self.label_20)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem5)
        self.epsLineEdit = QtWidgets.QLineEdit(self.widget)
        self.epsLineEdit.setObjectName("epsLineEdit")
        self.horizontalLayout_27.addWidget(self.epsLineEdit)
        self.verticalLayout_14.addWidget(self.widget)
        self.muWidget = QtWidgets.QWidget(self.tabWidgetPage1)
        self.muWidget.setObjectName("muWidget")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.muWidget)
        self.horizontalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_37.setSpacing(0)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_26 = QtWidgets.QLabel(self.muWidget)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_37.addWidget(self.label_26)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem6)
        self.muLineEdit = QtWidgets.QLineEdit(self.muWidget)
        self.muLineEdit.setObjectName("muLineEdit")
        self.horizontalLayout_37.addWidget(self.muLineEdit)
        self.verticalLayout_14.addWidget(self.muWidget)
        self.lamepsWidget = QtWidgets.QWidget(self.tabWidgetPage1)
        self.lamepsWidget.setObjectName("lamepsWidget")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.lamepsWidget)
        self.horizontalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_38.setSpacing(0)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_27 = QtWidgets.QLabel(self.lamepsWidget)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_38.addWidget(self.label_27)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem7)
        self.lamepsLineEdit = QtWidgets.QLineEdit(self.lamepsWidget)
        self.lamepsLineEdit.setObjectName("lamepsLineEdit")
        self.horizontalLayout_38.addWidget(self.lamepsLineEdit)
        self.verticalLayout_14.addWidget(self.lamepsWidget)
        self.verticalLayout_11.addLayout(self.verticalLayout_14)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setSpacing(0)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_28 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_40.addWidget(self.label_28)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem8)
        self.tolEdit = QtWidgets.QDoubleSpinBox(self.tabWidgetPage1)
        self.tolEdit.setMaximum(100.0)
        self.tolEdit.setProperty("value", 99.99)
        self.tolEdit.setObjectName("tolEdit")
        self.horizontalLayout_40.addWidget(self.tolEdit)
        self.verticalLayout_11.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setSpacing(0)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_29 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_41.addWidget(self.label_29)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem9)
        self.iterEdit = QtWidgets.QSpinBox(self.tabWidgetPage1)
        self.iterEdit.setMaximum(1000)
        self.iterEdit.setSingleStep(100)
        self.iterEdit.setProperty("value", 100)
        self.iterEdit.setObjectName("iterEdit")
        self.horizontalLayout_41.addWidget(self.iterEdit)
        self.verticalLayout_11.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem10)
        self.sigsegButton = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.sigsegButton.setObjectName("sigsegButton")
        self.horizontalLayout_23.addWidget(self.sigsegButton)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem11)
        self.verticalLayout_11.addLayout(self.horizontalLayout_23)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem12)
        self.tabWidget_2.addTab(self.tabWidgetPage1, "")
        self.verticalLayout_10.addWidget(self.tabWidget_2)
        spacerItem13 = QtWidgets.QSpacerItem(20, 86, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem13)
        self.toolBox.addItem(self.page_3, "")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 303, 428))
        self.page.setObjectName("page")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.polyBox = QtWidgets.QSpinBox(self.page)
        self.polyBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.polyBox.setMaximum(10)
        self.polyBox.setProperty("value", 1)
        self.polyBox.setObjectName("polyBox")
        self.horizontalLayout_4.addWidget(self.polyBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.periodEdit = QtWidgets.QLineEdit(self.page)
        self.periodEdit.setObjectName("periodEdit")
        self.horizontalLayout_5.addWidget(self.periodEdit)
        self.periodUnitLabel = QtWidgets.QLabel(self.page)
        self.periodUnitLabel.setObjectName("periodUnitLabel")
        self.horizontalLayout_5.addWidget(self.periodUnitLabel)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem16)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem17)
        self.sigmaEdit = QtWidgets.QLineEdit(self.groupBox)
        self.sigmaEdit.setObjectName("sigmaEdit")
        self.horizontalLayout_11.addWidget(self.sigmaEdit)
        self.sigmaUintLabel = QtWidgets.QLabel(self.groupBox)
        self.sigmaUintLabel.setObjectName("sigmaUintLabel")
        self.horizontalLayout_11.addWidget(self.sigmaUintLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem18)
        self.iqrFactorBox = QtWidgets.QSpinBox(self.groupBox)
        self.iqrFactorBox.setMaximum(5)
        self.iqrFactorBox.setProperty("value", 0)
        self.iqrFactorBox.setObjectName("iqrFactorBox")
        self.horizontalLayout_12.addWidget(self.iqrFactorBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_13.addWidget(self.label_10)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem19)
        self.iqrWindowBox = QtWidgets.QSpinBox(self.groupBox)
        self.iqrWindowBox.setMaximum(1000)
        self.iqrWindowBox.setProperty("value", 365)
        self.iqrWindowBox.setObjectName("iqrWindowBox")
        self.horizontalLayout_13.addWidget(self.iqrWindowBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.outliersButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outliersButton.sizePolicy().hasHeightForWidth())
        self.outliersButton.setSizePolicy(sizePolicy)
        self.outliersButton.setObjectName("outliersButton")
        self.horizontalLayout.addWidget(self.outliersButton)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.page)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.fitCheck = QtWidgets.QRadioButton(self.groupBox_2)
        self.fitCheck.setChecked(True)
        self.fitCheck.setObjectName("fitCheck")
        self.verticalLayout_5.addWidget(self.fitCheck)
        self.noOffsetsRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.noOffsetsRadio.setObjectName("noOffsetsRadio")
        self.verticalLayout_5.addWidget(self.noOffsetsRadio)
        self.residualCheck = QtWidgets.QRadioButton(self.groupBox_2)
        self.residualCheck.setObjectName("residualCheck")
        self.verticalLayout_5.addWidget(self.residualCheck)
        self.horizontalLayout_14.addLayout(self.verticalLayout_5)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem20)
        self.detrendButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detrendButton.sizePolicy().hasHeightForWidth())
        self.detrendButton.setSizePolicy(sizePolicy)
        self.detrendButton.setObjectName("detrendButton")
        self.horizontalLayout_14.addWidget(self.detrendButton)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem21)
        self.saveButton = QtWidgets.QPushButton(self.page)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_17.addWidget(self.saveButton)
        self.tsDataBox = QtWidgets.QComboBox(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsDataBox.sizePolicy().hasHeightForWidth())
        self.tsDataBox.setSizePolicy(sizePolicy)
        self.tsDataBox.setObjectName("tsDataBox")
        self.horizontalLayout_17.addWidget(self.tsDataBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        spacerItem22 = QtWidgets.QSpacerItem(20, 169, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem22)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 294, 417))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_11 = QtWidgets.QLabel(self.page_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_16.addWidget(self.label_11)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem23)
        self.spMethodBox = QtWidgets.QComboBox(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spMethodBox.sizePolicy().hasHeightForWidth())
        self.spMethodBox.setSizePolicy(sizePolicy)
        self.spMethodBox.setObjectName("spMethodBox")
        self.spMethodBox.addItem("")
        self.horizontalLayout_16.addWidget(self.spMethodBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.fftWidget = QtWidgets.QWidget(self.page_2)
        self.fftWidget.setObjectName("fftWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.fftWidget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_14 = QtWidgets.QLabel(self.fftWidget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_19.addWidget(self.label_14)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem24)
        self.fftWindowBox = QtWidgets.QComboBox(self.fftWidget)
        self.fftWindowBox.setObjectName("fftWindowBox")
        self.fftWindowBox.addItem("")
        self.horizontalLayout_19.addWidget(self.fftWindowBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_15 = QtWidgets.QLabel(self.fftWidget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_20.addWidget(self.label_15)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem25)
        self.fftWidthBox = QtWidgets.QDoubleSpinBox(self.fftWidget)
        self.fftWidthBox.setDecimals(1)
        self.fftWidthBox.setMaximum(1.0)
        self.fftWidthBox.setProperty("value", 0.1)
        self.fftWidthBox.setObjectName("fftWidthBox")
        self.horizontalLayout_20.addWidget(self.fftWidthBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.verticalLayout_4.addWidget(self.fftWidget)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.page_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem26)
        self.spDataBox = QtWidgets.QComboBox(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spDataBox.sizePolicy().hasHeightForWidth())
        self.spDataBox.setSizePolicy(sizePolicy)
        self.spDataBox.setObjectName("spDataBox")
        self.spDataBox.addItem("")
        self.spDataBox.addItem("")
        self.horizontalLayout_8.addWidget(self.spDataBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_12 = QtWidgets.QLabel(self.page_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.spLogFitCheck = QtWidgets.QCheckBox(self.page_2)
        self.spLogFitCheck.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.spLogFitCheck.setText("")
        self.spLogFitCheck.setObjectName("spLogFitCheck")
        self.horizontalLayout_9.addWidget(self.spLogFitCheck)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem27)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem28)
        self.spAnalysisButton = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spAnalysisButton.sizePolicy().hasHeightForWidth())
        self.spAnalysisButton.setSizePolicy(sizePolicy)
        self.spAnalysisButton.setObjectName("spAnalysisButton")
        self.horizontalLayout_15.addWidget(self.spAnalysisButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        spacerItem29 = QtWidgets.QSpacerItem(20, 215, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem29)
        self.toolBox.addItem(self.page_2, "")
        self.gridLayout_10.addWidget(self.toolBox, 0, 0, 1, 1)
        self.analysisDock.setWidget(self.dockWidgetContents)
        self.consoleDock = QtWidgets.QDockWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.consoleDock.sizePolicy().hasHeightForWidth())
        self.consoleDock.setSizePolicy(sizePolicy)
        self.consoleDock.setMinimumSize(QtCore.QSize(80, 98))
        self.consoleDock.setMaximumSize(QtCore.QSize(300, 524287))
        self.consoleDock.setObjectName("consoleDock")
        self.dockWidgetContents_7 = QtWidgets.QWidget()
        self.dockWidgetContents_7.setObjectName("dockWidgetContents_7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dockWidgetContents_7)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.consoleEdit = QtWidgets.QPlainTextEdit(self.dockWidgetContents_7)
        self.consoleEdit.setStyleSheet("font: 8pt \"Microsoft YaHei UI\";")
        self.consoleEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.consoleEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.consoleEdit.setReadOnly(True)
        self.consoleEdit.setObjectName("consoleEdit")
        self.gridLayout_3.addWidget(self.consoleEdit, 0, 0, 1, 1)
        self.consoleDock.setWidget(self.dockWidgetContents_7)
        self.gridLayout_9.addWidget(self.splitter_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1344, 27))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuSettings = QtWidgets.QMenu(self.menuMenu)
        self.menuSettings.setObjectName("menuSettings")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuBatch = QtWidgets.QMenu(self.menubar)
        self.menuBatch.setObjectName("menuBatch")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.fileDock = QtWidgets.QDockWidget(MainWindow)
        self.fileDock.setObjectName("fileDock")
        self.dockWidgetContents_5 = QtWidgets.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.dockWidgetContents_5)
        self.verticalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(3, -1, 3, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.dockWidgetContents_5)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem30)
        self.addFilesButton = QtWidgets.QToolButton(self.dockWidgetContents_5)
        self.addFilesButton.setText("")
        self.addFilesButton.setObjectName("addFilesButton")
        self.horizontalLayout_2.addWidget(self.addFilesButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.filesListWidget = QtWidgets.QListWidget(self.dockWidgetContents_5)
        self.filesListWidget.setDragEnabled(False)
        self.filesListWidget.setDragDropOverwriteMode(False)
        self.filesListWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.filesListWidget.setObjectName("filesListWidget")
        self.verticalLayout.addWidget(self.filesListWidget)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(3, 3, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.prevButton = QtWidgets.QToolButton(self.dockWidgetContents_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevButton.sizePolicy().hasHeightForWidth())
        self.prevButton.setSizePolicy(sizePolicy)
        self.prevButton.setObjectName("prevButton")
        self.horizontalLayout_10.addWidget(self.prevButton)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem31)
        self.deleteButton = QtWidgets.QPushButton(self.dockWidgetContents_5)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout_10.addWidget(self.deleteButton)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem32)
        self.nextButton = QtWidgets.QToolButton(self.dockWidgetContents_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextButton.sizePolicy().hasHeightForWidth())
        self.nextButton.setSizePolicy(sizePolicy)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_10.addWidget(self.nextButton)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.dockWidgetContents_5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.tsTab = QtWidgets.QTabWidget(self.dockWidgetContents_5)
        self.tsTab.setObjectName("tsTab")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(3, -1, 3, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem33)
        self.offsetStationLabel = QtWidgets.QLabel(self.tab_4)
        self.offsetStationLabel.setText("")
        self.offsetStationLabel.setObjectName("offsetStationLabel")
        self.horizontalLayout_7.addWidget(self.offsetStationLabel)
        self.gridLayout.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.offsetsListWidget = QtWidgets.QListWidget(self.tab_4)
        self.offsetsListWidget.setObjectName("offsetsListWidget")
        self.gridLayout.addWidget(self.offsetsListWidget, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem34)
        self.writeOffsetsButton = QtWidgets.QPushButton(self.tab_4)
        self.writeOffsetsButton.setObjectName("writeOffsetsButton")
        self.horizontalLayout_6.addWidget(self.writeOffsetsButton)
        self.gridLayout.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        self.tsTab.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.statisticsEdit = QtWidgets.QPlainTextEdit(self.tab_3)
        self.statisticsEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.statisticsEdit.setReadOnly(True)
        self.statisticsEdit.setObjectName("statisticsEdit")
        self.gridLayout_8.addWidget(self.statisticsEdit, 1, 0, 1, 1)
        self.tsTab.addTab(self.tab_3, "")
        self.verticalLayout_7.addWidget(self.tsTab)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents_5)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.offsetEdit = QtWidgets.QLineEdit(self.dockWidgetContents_5)
        self.offsetEdit.setReadOnly(True)
        self.offsetEdit.setObjectName("offsetEdit")
        self.verticalLayout_6.addWidget(self.offsetEdit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.addOffsetButton = QtWidgets.QToolButton(self.dockWidgetContents_5)
        self.addOffsetButton.setText("")
        self.addOffsetButton.setObjectName("addOffsetButton")
        self.verticalLayout_3.addWidget(self.addOffsetButton)
        self.deleteOffsetButton = QtWidgets.QToolButton(self.dockWidgetContents_5)
        self.deleteOffsetButton.setText("")
        self.deleteOffsetButton.setObjectName("deleteOffsetButton")
        self.verticalLayout_3.addWidget(self.deleteOffsetButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.fileDock.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.fileDock)
        self.actionZoom = QtWidgets.QAction(MainWindow)
        self.actionZoom.setCheckable(True)
        self.actionZoom.setChecked(False)
        self.actionZoom.setObjectName("actionZoom")
        self.actionPan = QtWidgets.QAction(MainWindow)
        self.actionPan.setCheckable(True)
        self.actionPan.setObjectName("actionPan")
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setCheckable(True)
        self.actionFile.setChecked(True)
        self.actionFile.setObjectName("actionFile")
        self.actionConsole = QtWidgets.QAction(MainWindow)
        self.actionConsole.setCheckable(True)
        self.actionConsole.setChecked(True)
        self.actionConsole.setObjectName("actionConsole")
        self.actionDetrendLog = QtWidgets.QAction(MainWindow)
        self.actionDetrendLog.setCheckable(True)
        self.actionDetrendLog.setChecked(True)
        self.actionDetrendLog.setObjectName("actionDetrendLog")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionDate = QtWidgets.QAction(MainWindow)
        self.actionDate.setObjectName("actionDate")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionDefault = QtWidgets.QAction(MainWindow)
        self.actionDefault.setObjectName("actionDefault")
        self.actionUser = QtWidgets.QAction(MainWindow)
        self.actionUser.setObjectName("actionUser")
        self.actionAnalysis = QtWidgets.QAction(MainWindow)
        self.actionAnalysis.setCheckable(True)
        self.actionAnalysis.setChecked(True)
        self.actionAnalysis.setObjectName("actionAnalysis")
        self.actionInterpolation = QtWidgets.QAction(MainWindow)
        self.actionInterpolation.setObjectName("actionInterpolation")
        self.actionHeader = QtWidgets.QAction(MainWindow)
        self.actionHeader.setObjectName("actionHeader")
        self.actionDetrend = QtWidgets.QAction(MainWindow)
        self.actionDetrend.setObjectName("actionDetrend")
        self.actionFigure = QtWidgets.QAction(MainWindow)
        self.actionFigure.setObjectName("actionFigure")
        self.actionOffsets = QtWidgets.QAction(MainWindow)
        self.actionOffsets.setCheckable(True)
        self.actionOffsets.setChecked(False)
        self.actionOffsets.setObjectName("actionOffsets")
        self.menuSettings.addAction(self.actionDefault)
        self.menuSettings.addAction(self.actionUser)
        self.menuMenu.addAction(self.actionOpen)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.menuSettings.menuAction())
        self.menuView.addAction(self.actionAnalysis)
        self.menuView.addAction(self.actionConsole)
        self.menuView.addAction(self.actionFile)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionDetrendLog)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionHelp)
        self.menuTools.addAction(self.actionOffsets)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionHeader)
        self.menuTools.addAction(self.actionDate)
        self.menuBatch.addAction(self.actionDetrend)
        self.menuBatch.addAction(self.actionFigure)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuBatch.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(1)
        self.tsTab.setCurrentIndex(0)
        self.actionFile.triggered['bool'].connect(self.fileDock.setVisible)
        self.actionConsole.triggered['bool'].connect(self.consoleDock.setVisible)
        self.actionAnalysis.triggered['bool'].connect(self.analysisDock.setVisible)
        self.analysisDock.visibilityChanged['bool'].connect(self.actionAnalysis.setChecked)
        self.consoleDock.visibilityChanged['bool'].connect(self.actionConsole.setChecked)
        self.fileDock.visibilityChanged['bool'].connect(self.actionFile.setChecked)
        self.actionOpen.triggered.connect(self.addFilesButton.click)
        self.msRadio.toggled['bool'].connect(self.betaWidget.setVisible)
        self.msRadio.toggled['bool'].connect(self.gammaWidget.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Time Domain Analysis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Spectral Domain Analysis"))
        self.analysisDock.setWindowTitle(_translate("MainWindow", "Analysis"))
        self.diffButton.setText(_translate("MainWindow", "Diff"))
        self.cumsumButton.setText(_translate("MainWindow", "Cumsum"))
        self.msRadio.setText(_translate("MainWindow", "Mumford-Shah"))
        self.bzRadio.setText(_translate("MainWindow", "Blake-Zisserman"))
        self.label_23.setText(_translate("MainWindow", "alpha"))
        self.alphaLineEdit.setText(_translate("MainWindow", "5"))
        self.label_24.setText(_translate("MainWindow", "beta"))
        self.betaLineEdit.setText(_translate("MainWindow", "0"))
        self.label_25.setText(_translate("MainWindow", "gamma"))
        self.gammaLineEdit.setText(_translate("MainWindow", "0"))
        self.label_20.setText(_translate("MainWindow", "epslion"))
        self.epsLineEdit.setText(_translate("MainWindow", "0.001"))
        self.label_26.setText(_translate("MainWindow", "mu_epslion"))
        self.muLineEdit.setText(_translate("MainWindow", "0.001"))
        self.label_27.setText(_translate("MainWindow", "lambda_epslion"))
        self.lamepsLineEdit.setText(_translate("MainWindow", "0.001"))
        self.label_28.setText(_translate("MainWindow", "tol"))
        self.label_29.setText(_translate("MainWindow", "iterative"))
        self.sigsegButton.setText(_translate("MainWindow", "Sigseg"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidgetPage1), _translate("MainWindow", "Sigseg"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Offsets Detection"))
        self.label_4.setText(_translate("MainWindow", "Polynomials"))
        self.label_3.setText(_translate("MainWindow", "Periods"))
        self.periodEdit.setText(_translate("MainWindow", "0.5 1"))
        self.periodUnitLabel.setText(_translate("MainWindow", "year"))
        self.groupBox.setTitle(_translate("MainWindow", "Outliers"))
        self.label_7.setText(_translate("MainWindow", "Sigma"))
        self.sigmaEdit.setText(_translate("MainWindow", "30 30 30"))
        self.sigmaUintLabel.setText(_translate("MainWindow", "(mm)"))
        self.label_9.setText(_translate("MainWindow", "IQR factor"))
        self.label_10.setText(_translate("MainWindow", "IQR window"))
        self.outliersButton.setText(_translate("MainWindow", "Clean"))
        self.outliersButton.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Analysis"))
        self.fitCheck.setText(_translate("MainWindow", "Fit"))
        self.noOffsetsRadio.setToolTip(_translate("MainWindow", "Offsets have been removed."))
        self.noOffsetsRadio.setText(_translate("MainWindow", "Continuous"))
        self.residualCheck.setText(_translate("MainWindow", "Residuals"))
        self.detrendButton.setText(_translate("MainWindow", "Detrend"))
        self.detrendButton.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.saveButton.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Time Domain Analysis"))
        self.label_11.setText(_translate("MainWindow", "Method"))
        self.spMethodBox.setItemText(0, _translate("MainWindow", "Lomb-Scargle"))
        self.label_14.setText(_translate("MainWindow", "Window Type"))
        self.fftWindowBox.setItemText(0, _translate("MainWindow", "Hamming"))
        self.label_15.setText(_translate("MainWindow", "Lenght"))
        self.label_6.setText(_translate("MainWindow", "Data"))
        self.spDataBox.setItemText(0, _translate("MainWindow", "Originals"))
        self.spDataBox.setItemText(1, _translate("MainWindow", "Residuals"))
        self.label_12.setText(_translate("MainWindow", "Log-log fit"))
        self.spAnalysisButton.setText(_translate("MainWindow", "Spectral Analysis"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Spectral Domain Analysis"))
        self.consoleDock.setWindowTitle(_translate("MainWindow", "Console"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuBatch.setTitle(_translate("MainWindow", "Batch"))
        self.fileDock.setWindowTitle(_translate("MainWindow", "File"))
        self.label.setText(_translate("MainWindow", "Add Files"))
        self.addFilesButton.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.filesListWidget.setSortingEnabled(True)
        self.prevButton.setText(_translate("MainWindow", "<"))
        self.prevButton.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.deleteButton.setShortcut(_translate("MainWindow", "Del"))
        self.nextButton.setText(_translate("MainWindow", ">"))
        self.nextButton.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.label_5.setText(_translate("MainWindow", "Station"))
        self.offsetsListWidget.setSortingEnabled(True)
        self.writeOffsetsButton.setText(_translate("MainWindow", "Write"))
        self.tsTab.setTabText(self.tsTab.indexOf(self.tab_4), _translate("MainWindow", "Offsets"))
        self.tsTab.setTabText(self.tsTab.indexOf(self.tab_3), _translate("MainWindow", "Statistics"))
        self.label_2.setText(_translate("MainWindow", "Offsets"))
        self.actionZoom.setText(_translate("MainWindow", "zoom"))
        self.actionPan.setText(_translate("MainWindow", "pan"))
        self.actionFile.setText(_translate("MainWindow", "File Dock"))
        self.actionConsole.setText(_translate("MainWindow", "Console Dock"))
        self.actionDetrendLog.setText(_translate("MainWindow", "Show Detrend Log"))
        self.actionAbout.setText(_translate("MainWindow", "About "))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionDate.setText(_translate("MainWindow", "Date Conversion"))
        self.actionOpen.setText(_translate("MainWindow", "Open File"))
        self.actionDefault.setText(_translate("MainWindow", "Default"))
        self.actionUser.setText(_translate("MainWindow", "User"))
        self.actionAnalysis.setText(_translate("MainWindow", "Analysis Dock"))
        self.actionInterpolation.setText(_translate("MainWindow", "Data Interpolation"))
        self.actionHeader.setText(_translate("MainWindow", "Add Header Comments"))
        self.actionDetrend.setText(_translate("MainWindow", "Detrend"))
        self.actionFigure.setText(_translate("MainWindow", "Figures"))
        self.actionOffsets.setText(_translate("MainWindow", "Offsets Detection (Beta)"))

