# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TSAnalyzer/TSWidgets/offset.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(241, 191)
        Dialog.setMaximumSize(QtCore.QSize(300, 280))
        Dialog.setStyleSheet("")
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.offsetBox = QtWidgets.QComboBox(Dialog)
        self.offsetBox.setMaximumSize(QtCore.QSize(106, 16777215))
        self.offsetBox.setStyleSheet("font: 10")
        self.offsetBox.setObjectName("offsetBox")
        self.offsetBox.addItem("")
        self.offsetBox.addItem("")
        self.horizontalLayout.addWidget(self.offsetBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setMaximumSize(QtCore.QSize(106, 16777215))
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_4.addWidget(self.dateEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.eqGroup = QtWidgets.QGroupBox(Dialog)
        self.eqGroup.setObjectName("eqGroup")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.eqGroup)
        self.verticalLayout.setContentsMargins(3, -1, 3, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.eqRadio = QtWidgets.QRadioButton(self.eqGroup)
        self.eqRadio.setChecked(True)
        self.eqRadio.setObjectName("eqRadio")
        self.horizontalLayout_3.addWidget(self.eqRadio)
        self.expRadio = QtWidgets.QRadioButton(self.eqGroup)
        self.expRadio.setObjectName("expRadio")
        self.horizontalLayout_3.addWidget(self.expRadio)
        self.logRadio = QtWidgets.QRadioButton(self.eqGroup)
        self.logRadio.setObjectName("logRadio")
        self.horizontalLayout_3.addWidget(self.logRadio)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tauWidget = QtWidgets.QWidget(self.eqGroup)
        self.tauWidget.setObjectName("tauWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tauWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.taulLayout = QtWidgets.QHBoxLayout()
        self.taulLayout.setObjectName("taulLayout")
        self.label_3 = QtWidgets.QLabel(self.tauWidget)
        self.label_3.setObjectName("label_3")
        self.taulLayout.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.taulLayout.addItem(spacerItem2)
        self.tauBox = QtWidgets.QSpinBox(self.tauWidget)
        self.tauBox.setMaximum(99999)
        self.tauBox.setProperty("value", 1)
        self.tauBox.setObjectName("tauBox")
        self.taulLayout.addWidget(self.tauBox)
        self.gridLayout_2.addLayout(self.taulLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.tauWidget)
        self.verticalLayout_2.addWidget(self.eqGroup)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_5.addWidget(self.cancelButton)
        self.confirmButton = QtWidgets.QPushButton(Dialog)
        self.confirmButton.setObjectName("confirmButton")
        self.horizontalLayout_5.addWidget(self.confirmButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Offsets Editor"))
        self.label.setText(_translate("Dialog", "Offset Type"))
        self.offsetBox.setItemText(0, _translate("Dialog", "Equipment"))
        self.offsetBox.setItemText(1, _translate("Dialog", "Earthquake"))
        self.label_2.setText(_translate("Dialog", "Offset Date"))
        self.dateEdit.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.eqGroup.setTitle(_translate("Dialog", "Earthquake Type"))
        self.eqRadio.setText(_translate("Dialog", "Break"))
        self.expRadio.setText(_translate("Dialog", "Exp"))
        self.logRadio.setText(_translate("Dialog", "Log"))
        self.label_3.setText(_translate("Dialog", "Decay Tau"))
        self.cancelButton.setText(_translate("Dialog", "Delete"))
        self.confirmButton.setText(_translate("Dialog", "Confirm"))

