# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analysis_batch.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(860, 694)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setMargin(3)
        self.gridLayout_2.setSpacing(3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_22.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem)
        self.selectButton = QtGui.QPushButton(Dialog)
        self.selectButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.selectButton.setObjectName(_fromUtf8("selectButton"))
        self.horizontalLayout_22.addWidget(self.selectButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.listWidget = QtGui.QListWidget(Dialog)
        self.listWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.verticalLayout_7.addWidget(self.listWidget)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.countLabel = QtGui.QLabel(Dialog)
        self.countLabel.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.countLabel.setObjectName(_fromUtf8("countLabel"))
        self.horizontalLayout_15.addWidget(self.countLabel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.deleteButton = QtGui.QPushButton(Dialog)
        self.deleteButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.deleteButton.setObjectName(_fromUtf8("deleteButton"))
        self.horizontalLayout_15.addWidget(self.deleteButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.dockWidget = QtGui.QDockWidget(Dialog)
        self.dockWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_6 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.consoleEdit = QtGui.QPlainTextEdit(self.dockWidgetContents)
        self.consoleEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.consoleEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.consoleEdit.setFrameShadow(QtGui.QFrame.Raised)
        self.consoleEdit.setLineWrapMode(QtGui.QPlainTextEdit.WidgetWidth)
        self.consoleEdit.setReadOnly(True)
        self.consoleEdit.setObjectName(_fromUtf8("consoleEdit"))
        self.gridLayout_6.addWidget(self.consoleEdit, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.gridLayout_2.addWidget(self.dockWidget, 1, 0, 1, 2)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.offsetEdit = QtGui.QLineEdit(Dialog)
        self.offsetEdit.setEnabled(True)
        self.offsetEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.offsetEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.offsetEdit.setReadOnly(True)
        self.offsetEdit.setObjectName(_fromUtf8("offsetEdit"))
        self.horizontalLayout.addWidget(self.offsetEdit)
        self.offsetButton = QtGui.QToolButton(Dialog)
        self.offsetButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.offsetButton.setText(_fromUtf8(""))
        self.offsetButton.setObjectName(_fromUtf8("offsetButton"))
        self.horizontalLayout.addWidget(self.offsetButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.outlierGroup = QtGui.QGroupBox(Dialog)
        self.outlierGroup.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.outlierGroup.setFlat(False)
        self.outlierGroup.setCheckable(True)
        self.outlierGroup.setObjectName(_fromUtf8("outlierGroup"))
        self.gridLayout_4 = QtGui.QGridLayout(self.outlierGroup)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_7 = QtGui.QLabel(self.outlierGroup)
        self.label_7.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_8.addWidget(self.label_7)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.iqrWindowBox = QtGui.QSpinBox(self.outlierGroup)
        self.iqrWindowBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.iqrWindowBox.setMaximum(9999)
        self.iqrWindowBox.setProperty("value", 365)
        self.iqrWindowBox.setObjectName(_fromUtf8("iqrWindowBox"))
        self.horizontalLayout_8.addWidget(self.iqrWindowBox)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_5 = QtGui.QLabel(self.outlierGroup)
        self.label_5.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.sigmaEdit = QtGui.QLineEdit(self.outlierGroup)
        self.sigmaEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.sigmaEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.sigmaEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sigmaEdit.setInputMask(_fromUtf8(""))
        self.sigmaEdit.setObjectName(_fromUtf8("sigmaEdit"))
        self.horizontalLayout_6.addWidget(self.sigmaEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_19 = QtGui.QLabel(self.outlierGroup)
        self.label_19.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_2.addWidget(self.label_19)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.outlierDirEdit = QtGui.QLineEdit(self.outlierGroup)
        self.outlierDirEdit.setEnabled(True)
        self.outlierDirEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.outlierDirEdit.setReadOnly(True)
        self.outlierDirEdit.setObjectName(_fromUtf8("outlierDirEdit"))
        self.horizontalLayout_4.addWidget(self.outlierDirEdit)
        self.outlierDirButton = QtGui.QToolButton(self.outlierGroup)
        self.outlierDirButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.outlierDirButton.setText(_fromUtf8(""))
        self.outlierDirButton.setObjectName(_fromUtf8("outlierDirButton"))
        self.horizontalLayout_4.addWidget(self.outlierDirButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_6 = QtGui.QLabel(self.outlierGroup)
        self.label_6.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.iqrBox = QtGui.QSpinBox(self.outlierGroup)
        self.iqrBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.iqrBox.setMaximum(5)
        self.iqrBox.setProperty("value", 1)
        self.iqrBox.setObjectName(_fromUtf8("iqrBox"))
        self.horizontalLayout_7.addWidget(self.iqrBox)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_20 = QtGui.QLabel(self.outlierGroup)
        self.label_20.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_19.addWidget(self.label_20)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem5)
        self.outlierNameEdit = QtGui.QLineEdit(self.outlierGroup)
        self.outlierNameEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.outlierNameEdit.setObjectName(_fromUtf8("outlierNameEdit"))
        self.horizontalLayout_19.addWidget(self.outlierNameEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_19, 4, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.outlierGroup)
        self.analysisGroup = QtGui.QGroupBox(Dialog)
        self.analysisGroup.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.analysisGroup.setCheckable(True)
        self.analysisGroup.setObjectName(_fromUtf8("analysisGroup"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.analysisGroup)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_8 = QtGui.QLabel(self.analysisGroup)
        self.label_8.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_24.addWidget(self.label_8)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem6)
        self.polyBox = QtGui.QSpinBox(self.analysisGroup)
        self.polyBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.polyBox.setProperty("value", 1)
        self.polyBox.setObjectName(_fromUtf8("polyBox"))
        self.horizontalLayout_24.addWidget(self.polyBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_9 = QtGui.QLabel(self.analysisGroup)
        self.label_9.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_25.addWidget(self.label_9)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem7)
        self.periodEdit = QtGui.QLineEdit(self.analysisGroup)
        self.periodEdit.setEnabled(True)
        self.periodEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.periodEdit.setObjectName(_fromUtf8("periodEdit"))
        self.horizontalLayout_25.addWidget(self.periodEdit)
        self.verticalLayout_9.addLayout(self.horizontalLayout_25)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_10 = QtGui.QLabel(self.analysisGroup)
        self.label_10.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_3.addWidget(self.label_10)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.logDirEdit = QtGui.QLineEdit(self.analysisGroup)
        self.logDirEdit.setEnabled(True)
        self.logDirEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.logDirEdit.setReadOnly(True)
        self.logDirEdit.setObjectName(_fromUtf8("logDirEdit"))
        self.horizontalLayout_5.addWidget(self.logDirEdit)
        self.logDirButton = QtGui.QToolButton(self.analysisGroup)
        self.logDirButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.logDirButton.setText(_fromUtf8(""))
        self.logDirButton.setObjectName(_fromUtf8("logDirButton"))
        self.horizontalLayout_5.addWidget(self.logDirButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_9.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_11 = QtGui.QLabel(self.analysisGroup)
        self.label_11.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_4.addWidget(self.label_11)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.saveDirEdit = QtGui.QLineEdit(self.analysisGroup)
        self.saveDirEdit.setEnabled(True)
        self.saveDirEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.saveDirEdit.setReadOnly(True)
        self.saveDirEdit.setObjectName(_fromUtf8("saveDirEdit"))
        self.horizontalLayout_9.addWidget(self.saveDirEdit)
        self.saveDirButton = QtGui.QToolButton(self.analysisGroup)
        self.saveDirButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.saveDirButton.setText(_fromUtf8(""))
        self.saveDirButton.setObjectName(_fromUtf8("saveDirButton"))
        self.horizontalLayout_9.addWidget(self.saveDirButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.verticalLayout_9.addLayout(self.verticalLayout_4)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_14 = QtGui.QLabel(self.analysisGroup)
        self.label_14.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_10.addWidget(self.label_14)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.saveNameEdit = QtGui.QLineEdit(self.analysisGroup)
        self.saveNameEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.saveNameEdit.setObjectName(_fromUtf8("saveNameEdit"))
        self.horizontalLayout_10.addWidget(self.saveNameEdit)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.verticalLayout_5.addWidget(self.analysisGroup)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.timeGroup = QtGui.QGroupBox(Dialog)
        self.timeGroup.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.timeGroup.setCheckable(True)
        self.timeGroup.setObjectName(_fromUtf8("timeGroup"))
        self.gridLayout = QtGui.QGridLayout(self.timeGroup)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.timeEdit = QtGui.QPlainTextEdit(self.timeGroup)
        self.timeEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.timeEdit.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.timeEdit.setObjectName(_fromUtf8("timeEdit"))
        self.gridLayout.addWidget(self.timeEdit, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.timeGroup)
        self.stackingGroup = QtGui.QGroupBox(Dialog)
        self.stackingGroup.setEnabled(False)
        self.stackingGroup.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.stackingGroup.setCheckable(True)
        self.stackingGroup.setObjectName(_fromUtf8("stackingGroup"))
        self.gridLayout_3 = QtGui.QGridLayout(self.stackingGroup)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.stackingGroup)
        self.label_4.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.cmeBox = QtGui.QComboBox(self.stackingGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmeBox.sizePolicy().hasHeightForWidth())
        self.cmeBox.setSizePolicy(sizePolicy)
        self.cmeBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cmeBox.setObjectName(_fromUtf8("cmeBox"))
        self.cmeBox.addItem(_fromUtf8(""))
        self.cmeBox.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.cmeBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_3 = QtGui.QLabel(self.stackingGroup)
        self.label_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_6.addWidget(self.label_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cmeEdit = QtGui.QLineEdit(self.stackingGroup)
        self.cmeEdit.setEnabled(False)
        self.cmeEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cmeEdit.setReadOnly(True)
        self.cmeEdit.setObjectName(_fromUtf8("cmeEdit"))
        self.horizontalLayout_2.addWidget(self.cmeEdit)
        self.cmeButton = QtGui.QToolButton(self.stackingGroup)
        self.cmeButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cmeButton.setText(_fromUtf8(""))
        self.cmeButton.setObjectName(_fromUtf8("cmeButton"))
        self.horizontalLayout_2.addWidget(self.cmeButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.stackingGroup)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_24 = QtGui.QLabel(Dialog)
        self.label_24.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_23.addWidget(self.label_24)
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_23.addWidget(self.progressBar)
        self.batchButton = QtGui.QPushButton(Dialog)
        self.batchButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.batchButton.setObjectName(_fromUtf8("batchButton"))
        self.horizontalLayout_23.addWidget(self.batchButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_23)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "TSAnalyzer Detrend", None))
        self.label.setText(_translate("Dialog", "Time Serie Files", None))
        self.selectButton.setText(_translate("Dialog", "Add", None))
        self.listWidget.setSortingEnabled(True)
        self.countLabel.setText(_translate("Dialog", "Total: 0", None))
        self.deleteButton.setText(_translate("Dialog", "Delete", None))
        self.dockWidget.setWindowTitle(_translate("Dialog", "Console", None))
        self.label_2.setText(_translate("Dialog", "Offsets File", None))
        self.outlierGroup.setTitle(_translate("Dialog", "Outlier", None))
        self.label_7.setText(_translate("Dialog", "Window", None))
        self.label_5.setText(_translate("Dialog", "Sigma", None))
        self.sigmaEdit.setText(_translate("Dialog", "30 30 30", None))
        self.label_19.setText(_translate("Dialog", "Save Dir", None))
        self.outlierDirEdit.setText(_translate("Dialog", "clean", None))
        self.label_6.setText(_translate("Dialog", "IQR Factor", None))
        self.label_20.setText(_translate("Dialog", "Data Name Suffix", None))
        self.outlierNameEdit.setText(_translate("Dialog", "clean", None))
        self.analysisGroup.setTitle(_translate("Dialog", "Analysis", None))
        self.label_8.setText(_translate("Dialog", "Polynomials", None))
        self.label_9.setText(_translate("Dialog", "Periods", None))
        self.periodEdit.setText(_translate("Dialog", "0.5 1", None))
        self.label_10.setText(_translate("Dialog", "Log Dir", None))
        self.logDirEdit.setText(_translate("Dialog", "log", None))
        self.label_11.setText(_translate("Dialog", "Save Dir", None))
        self.saveDirEdit.setText(_translate("Dialog", "residual", None))
        self.label_14.setText(_translate("Dialog", "Data Name Suffix", None))
        self.saveNameEdit.setText(_translate("Dialog", "residual", None))
        self.timeGroup.setTitle(_translate("Dialog", "Time Interval", None))
        self.timeEdit.setPlainText(_translate("Dialog", "# # stands for comment\n"
"# The first line if suit for whole time series file\n"
"# space between from start and end time\n"
"# format should be ymd(hms) can be omitted\n"
"20000101 20140101\n"
"# 200001011200 201401011200\n"
"# The following lines should be in the format\n"
"# site omit_start omit_end\n"
"tain 20000101 20140101", None))
        self.stackingGroup.setTitle(_translate("Dialog", "Regional Filtering", None))
        self.label_4.setText(_translate("Dialog", "Method", None))
        self.cmeBox.setItemText(0, _translate("Dialog", "Stacking", None))
        self.cmeBox.setItemText(1, _translate("Dialog", "PCA", None))
        self.label_3.setText(_translate("Dialog", "Common Mode Errors", None))
        self.label_24.setText(_translate("Dialog", "Progress", None))
        self.batchButton.setText(_translate("Dialog", "Batch", None))

