# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'figure_batch.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(818, 817)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setMargin(3)
        self.gridLayout_2.setSpacing(3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.splitter = QtGui.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_22.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem)
        self.selectButton = QtGui.QPushButton(self.layoutWidget)
        self.selectButton.setText(_fromUtf8(""))
        self.selectButton.setObjectName(_fromUtf8("selectButton"))
        self.horizontalLayout_22.addWidget(self.selectButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.listWidget = QtGui.QListWidget(self.layoutWidget)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.verticalLayout_7.addWidget(self.listWidget)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.deleteButton = QtGui.QPushButton(self.layoutWidget)
        self.deleteButton.setObjectName(_fromUtf8("deleteButton"))
        self.horizontalLayout_15.addWidget(self.deleteButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.countLabel = QtGui.QLabel(self.layoutWidget)
        self.countLabel.setObjectName(_fromUtf8("countLabel"))
        self.horizontalLayout_15.addWidget(self.countLabel)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setMargin(3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setMargin(6)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.dpiBox = QtGui.QSpinBox(self.groupBox)
        self.dpiBox.setMinimum(100)
        self.dpiBox.setMaximum(999)
        self.dpiBox.setSingleStep(10)
        self.dpiBox.setProperty("value", 300)
        self.dpiBox.setObjectName(_fromUtf8("dpiBox"))
        self.horizontalLayout_2.addWidget(self.dpiBox)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.errorBarCheck = QtGui.QCheckBox(self.groupBox)
        self.errorBarCheck.setText(_fromUtf8(""))
        self.errorBarCheck.setObjectName(_fromUtf8("errorBarCheck"))
        self.horizontalLayout_3.addWidget(self.errorBarCheck)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.offsetsEdit = QtGui.QLineEdit(self.groupBox)
        self.offsetsEdit.setReadOnly(True)
        self.offsetsEdit.setObjectName(_fromUtf8("offsetsEdit"))
        self.horizontalLayout_5.addWidget(self.offsetsEdit)
        self.offsetsButton = QtGui.QToolButton(self.groupBox)
        self.offsetsButton.setText(_fromUtf8(""))
        self.offsetsButton.setObjectName(_fromUtf8("offsetsButton"))
        self.horizontalLayout_5.addWidget(self.offsetsButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 0, 1, 2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.dirEdit = QtGui.QLineEdit(self.groupBox)
        self.dirEdit.setReadOnly(True)
        self.dirEdit.setObjectName(_fromUtf8("dirEdit"))
        self.horizontalLayout_4.addWidget(self.dirEdit)
        self.saveDirButton = QtGui.QToolButton(self.groupBox)
        self.saveDirButton.setText(_fromUtf8(""))
        self.saveDirButton.setObjectName(_fromUtf8("saveDirButton"))
        self.horizontalLayout_4.addWidget(self.saveDirButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout, 3, 0, 1, 2)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setContentsMargins(0, 9, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.imageLabel = QtGui.QLabel(self.groupBox_2)
        self.imageLabel.setMinimumSize(QtCore.QSize(500, 500))
        self.imageLabel.setMaximumSize(QtCore.QSize(500, 500))
        self.imageLabel.setText(_fromUtf8(""))
        self.imageLabel.setObjectName(_fromUtf8("imageLabel"))
        self.verticalLayout_3.addWidget(self.imageLabel)
        self.consoleEdit = QtGui.QPlainTextEdit(self.groupBox_2)
        self.consoleEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.consoleEdit.setFrameShadow(QtGui.QFrame.Raised)
        self.consoleEdit.setLineWrapMode(QtGui.QPlainTextEdit.WidgetWidth)
        self.consoleEdit.setReadOnly(True)
        self.consoleEdit.setObjectName(_fromUtf8("consoleEdit"))
        self.verticalLayout_3.addWidget(self.consoleEdit)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_24 = QtGui.QLabel(self.layoutWidget1)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_23.addWidget(self.label_24)
        self.progressBar = QtGui.QProgressBar(self.layoutWidget1)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_23.addWidget(self.progressBar)
        self.batchButton = QtGui.QPushButton(self.layoutWidget1)
        self.batchButton.setObjectName(_fromUtf8("batchButton"))
        self.horizontalLayout_23.addWidget(self.batchButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_23)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "TSAnalyzer Figures", None))
        self.label.setText(_translate("Dialog", "Time Serie Files", None))
        self.listWidget.setSortingEnabled(True)
        self.deleteButton.setText(_translate("Dialog", "Delete", None))
        self.countLabel.setText(_translate("Dialog", "Total: 0", None))
        self.groupBox.setTitle(_translate("Dialog", "Figure Settings", None))
        self.label_2.setText(_translate("Dialog", "Figure Format", None))
        self.comboBox.setItemText(0, _translate("Dialog", "png", None))
        self.comboBox.setItemText(1, _translate("Dialog", "eps", None))
        self.comboBox.setItemText(2, _translate("Dialog", "jpg", None))
        self.comboBox.setItemText(3, _translate("Dialog", "pdf", None))
        self.label_3.setText(_translate("Dialog", "Figure DPI", None))
        self.label_4.setText(_translate("Dialog", "ErrorBar", None))
        self.label_6.setText(_translate("Dialog", "Offsets", None))
        self.label_5.setText(_translate("Dialog", "Save Directory", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Console", None))
        self.label_24.setText(_translate("Dialog", "Progress", None))
        self.batchButton.setText(_translate("Dialog", "Batch", None))

