# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1200, 800)
        MainWindow.setStyleSheet(_fromUtf8(""))
        MainWindow.setTabShape(QtGui.QTabWidget.Triangular)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_9 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setSpacing(3)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.splitter_3 = QtGui.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.tabWidget = QtGui.QTabWidget(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet(_fromUtf8("DockWidget::title {\n"
"    font: bold;\n"
"}"))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setAutoFillBackground(True)
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tsPlotWidget = MatplotlibWidget(self.tab)
        self.tsPlotWidget.setObjectName(_fromUtf8("tsPlotWidget"))
        self.gridLayout_2.addWidget(self.tsPlotWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.spPlotWidget = MatplotlibWidget(self.tab_2)
        self.spPlotWidget.setObjectName(_fromUtf8("spPlotWidget"))
        self.gridLayout_4.addWidget(self.spPlotWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.splitter_2 = QtGui.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.analysisDock = QtGui.QDockWidget(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analysisDock.sizePolicy().hasHeightForWidth())
        self.analysisDock.setSizePolicy(sizePolicy)
        self.analysisDock.setMinimumSize(QtCore.QSize(80, 149))
        self.analysisDock.setMaximumSize(QtCore.QSize(300, 524287))
        self.analysisDock.setObjectName(_fromUtf8("analysisDock"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_10 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_10.setMargin(3)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.toolBox = QtGui.QToolBox(self.dockWidgetContents)
        self.toolBox.setStyleSheet(_fromUtf8(""))
        self.toolBox.setFrameShape(QtGui.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtGui.QFrame.Plain)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 294, 394))
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.polyBox = QtGui.QSpinBox(self.page)
        self.polyBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.polyBox.setMaximum(10)
        self.polyBox.setProperty("value", 1)
        self.polyBox.setObjectName(_fromUtf8("polyBox"))
        self.horizontalLayout_4.addWidget(self.polyBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.page)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.periodEdit = QtGui.QLineEdit(self.page)
        self.periodEdit.setObjectName(_fromUtf8("periodEdit"))
        self.horizontalLayout_5.addWidget(self.periodEdit)
        self.periodUnitLabel = QtGui.QLabel(self.page)
        self.periodUnitLabel.setObjectName(_fromUtf8("periodUnitLabel"))
        self.horizontalLayout_5.addWidget(self.periodUnitLabel)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.groupBox = QtGui.QGroupBox(self.page)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_11.addWidget(self.label_7)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.sigmaEdit = QtGui.QLineEdit(self.groupBox)
        self.sigmaEdit.setObjectName(_fromUtf8("sigmaEdit"))
        self.horizontalLayout_11.addWidget(self.sigmaEdit)
        self.sigmaUintLabel = QtGui.QLabel(self.groupBox)
        self.sigmaUintLabel.setObjectName(_fromUtf8("sigmaUintLabel"))
        self.horizontalLayout_11.addWidget(self.sigmaUintLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_12.addWidget(self.label_9)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.iqrFactorBox = QtGui.QSpinBox(self.groupBox)
        self.iqrFactorBox.setMaximum(5)
        self.iqrFactorBox.setProperty("value", 0)
        self.iqrFactorBox.setObjectName(_fromUtf8("iqrFactorBox"))
        self.horizontalLayout_12.addWidget(self.iqrFactorBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_13.addWidget(self.label_10)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.iqrWindowBox = QtGui.QSpinBox(self.groupBox)
        self.iqrWindowBox.setMaximum(1000)
        self.iqrWindowBox.setProperty("value", 365)
        self.iqrWindowBox.setObjectName(_fromUtf8("iqrWindowBox"))
        self.horizontalLayout_13.addWidget(self.iqrWindowBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.outliersButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outliersButton.sizePolicy().hasHeightForWidth())
        self.outliersButton.setSizePolicy(sizePolicy)
        self.outliersButton.setObjectName(_fromUtf8("outliersButton"))
        self.horizontalLayout.addWidget(self.outliersButton)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.page)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.fitCheck = QtGui.QRadioButton(self.groupBox_2)
        self.fitCheck.setChecked(True)
        self.fitCheck.setObjectName(_fromUtf8("fitCheck"))
        self.verticalLayout_5.addWidget(self.fitCheck)
        self.noOffsetsRadio = QtGui.QRadioButton(self.groupBox_2)
        self.noOffsetsRadio.setObjectName(_fromUtf8("noOffsetsRadio"))
        self.verticalLayout_5.addWidget(self.noOffsetsRadio)
        self.residualCheck = QtGui.QRadioButton(self.groupBox_2)
        self.residualCheck.setObjectName(_fromUtf8("residualCheck"))
        self.verticalLayout_5.addWidget(self.residualCheck)
        self.horizontalLayout_14.addLayout(self.verticalLayout_5)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.detrendButton = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detrendButton.sizePolicy().hasHeightForWidth())
        self.detrendButton.setSizePolicy(sizePolicy)
        self.detrendButton.setObjectName(_fromUtf8("detrendButton"))
        self.horizontalLayout_14.addWidget(self.detrendButton)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem7)
        self.saveButton = QtGui.QPushButton(self.page)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.horizontalLayout_17.addWidget(self.saveButton)
        self.tsDataBox = QtGui.QComboBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsDataBox.sizePolicy().hasHeightForWidth())
        self.tsDataBox.setSizePolicy(sizePolicy)
        self.tsDataBox.setObjectName(_fromUtf8("tsDataBox"))
        self.horizontalLayout_17.addWidget(self.tsDataBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        spacerItem8 = QtGui.QSpacerItem(20, 169, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem8)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 294, 394))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_11 = QtGui.QLabel(self.page_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_16.addWidget(self.label_11)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem9)
        self.spMethodBox = QtGui.QComboBox(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spMethodBox.sizePolicy().hasHeightForWidth())
        self.spMethodBox.setSizePolicy(sizePolicy)
        self.spMethodBox.setObjectName(_fromUtf8("spMethodBox"))
        self.spMethodBox.addItem(_fromUtf8(""))
        self.horizontalLayout_16.addWidget(self.spMethodBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.fftWidget = QtGui.QWidget(self.page_2)
        self.fftWidget.setObjectName(_fromUtf8("fftWidget"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.fftWidget)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_14 = QtGui.QLabel(self.fftWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_19.addWidget(self.label_14)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem10)
        self.fftWindowBox = QtGui.QComboBox(self.fftWidget)
        self.fftWindowBox.setObjectName(_fromUtf8("fftWindowBox"))
        self.fftWindowBox.addItem(_fromUtf8(""))
        self.horizontalLayout_19.addWidget(self.fftWindowBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_15 = QtGui.QLabel(self.fftWidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_20.addWidget(self.label_15)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem11)
        self.fftWidthBox = QtGui.QDoubleSpinBox(self.fftWidget)
        self.fftWidthBox.setDecimals(1)
        self.fftWidthBox.setMaximum(1.0)
        self.fftWidthBox.setProperty("value", 0.1)
        self.fftWidthBox.setObjectName(_fromUtf8("fftWidthBox"))
        self.horizontalLayout_20.addWidget(self.fftWidthBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.verticalLayout_4.addWidget(self.fftWidget)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtGui.QLabel(self.page_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem12)
        self.spDataBox = QtGui.QComboBox(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spDataBox.sizePolicy().hasHeightForWidth())
        self.spDataBox.setSizePolicy(sizePolicy)
        self.spDataBox.setObjectName(_fromUtf8("spDataBox"))
        self.spDataBox.addItem(_fromUtf8(""))
        self.spDataBox.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.spDataBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_12 = QtGui.QLabel(self.page_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_9.addWidget(self.label_12)
        self.spLogFitCheck = QtGui.QCheckBox(self.page_2)
        self.spLogFitCheck.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.spLogFitCheck.setText(_fromUtf8(""))
        self.spLogFitCheck.setObjectName(_fromUtf8("spLogFitCheck"))
        self.horizontalLayout_9.addWidget(self.spLogFitCheck)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem13)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem14)
        self.spAnalysisButton = QtGui.QPushButton(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spAnalysisButton.sizePolicy().hasHeightForWidth())
        self.spAnalysisButton.setSizePolicy(sizePolicy)
        self.spAnalysisButton.setObjectName(_fromUtf8("spAnalysisButton"))
        self.horizontalLayout_15.addWidget(self.spAnalysisButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        spacerItem15 = QtGui.QSpacerItem(20, 215, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem15)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.gridLayout_10.addWidget(self.toolBox, 0, 0, 1, 1)
        self.analysisDock.setWidget(self.dockWidgetContents)
        self.consoleDock = QtGui.QDockWidget(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.consoleDock.sizePolicy().hasHeightForWidth())
        self.consoleDock.setSizePolicy(sizePolicy)
        self.consoleDock.setMinimumSize(QtCore.QSize(80, 91))
        self.consoleDock.setMaximumSize(QtCore.QSize(300, 524287))
        self.consoleDock.setObjectName(_fromUtf8("consoleDock"))
        self.dockWidgetContents_7 = QtGui.QWidget()
        self.dockWidgetContents_7.setObjectName(_fromUtf8("dockWidgetContents_7"))
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents_7)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.consoleEdit = QtGui.QPlainTextEdit(self.dockWidgetContents_7)
        self.consoleEdit.setStyleSheet(_fromUtf8("font: 8pt \"Microsoft YaHei UI\";"))
        self.consoleEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.consoleEdit.setLineWrapMode(QtGui.QPlainTextEdit.WidgetWidth)
        self.consoleEdit.setReadOnly(True)
        self.consoleEdit.setObjectName(_fromUtf8("consoleEdit"))
        self.gridLayout_3.addWidget(self.consoleEdit, 0, 0, 1, 1)
        self.consoleDock.setWidget(self.dockWidgetContents_7)
        self.gridLayout_9.addWidget(self.splitter_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuSettings = QtGui.QMenu(self.menuMenu)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuBatch = QtGui.QMenu(self.menubar)
        self.menuBatch.setObjectName(_fromUtf8("menuBatch"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.fileDock = QtGui.QDockWidget(MainWindow)
        self.fileDock.setObjectName(_fromUtf8("fileDock"))
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName(_fromUtf8("dockWidgetContents_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.dockWidgetContents_5)
        self.verticalLayout_7.setMargin(3)
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(3, -1, 3, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.dockWidgetContents_5)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem16)
        self.addFilesButton = QtGui.QToolButton(self.dockWidgetContents_5)
        self.addFilesButton.setText(_fromUtf8(""))
        self.addFilesButton.setObjectName(_fromUtf8("addFilesButton"))
        self.horizontalLayout_2.addWidget(self.addFilesButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.filesListWidget = QtGui.QListWidget(self.dockWidgetContents_5)
        self.filesListWidget.setObjectName(_fromUtf8("filesListWidget"))
        self.verticalLayout.addWidget(self.filesListWidget)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(3, 3, -1, -1)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.prevButton = QtGui.QToolButton(self.dockWidgetContents_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevButton.sizePolicy().hasHeightForWidth())
        self.prevButton.setSizePolicy(sizePolicy)
        self.prevButton.setObjectName(_fromUtf8("prevButton"))
        self.horizontalLayout_10.addWidget(self.prevButton)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem17)
        self.deleteButton = QtGui.QPushButton(self.dockWidgetContents_5)
        self.deleteButton.setObjectName(_fromUtf8("deleteButton"))
        self.horizontalLayout_10.addWidget(self.deleteButton)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem18)
        self.nextButton = QtGui.QToolButton(self.dockWidgetContents_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextButton.sizePolicy().hasHeightForWidth())
        self.nextButton.setSizePolicy(sizePolicy)
        self.nextButton.setObjectName(_fromUtf8("nextButton"))
        self.horizontalLayout_10.addWidget(self.nextButton)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.line = QtGui.QFrame(self.dockWidgetContents_5)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_7.addWidget(self.line)
        self.tsTab = QtGui.QTabWidget(self.dockWidgetContents_5)
        self.tsTab.setObjectName(_fromUtf8("tsTab"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout = QtGui.QGridLayout(self.tab_4)
        self.gridLayout.setMargin(3)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(3, -1, 3, -1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_5 = QtGui.QLabel(self.tab_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem19)
        self.offsetStationLabel = QtGui.QLabel(self.tab_4)
        self.offsetStationLabel.setText(_fromUtf8(""))
        self.offsetStationLabel.setObjectName(_fromUtf8("offsetStationLabel"))
        self.horizontalLayout_7.addWidget(self.offsetStationLabel)
        self.gridLayout.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.offsetsListWidget = QtGui.QListWidget(self.tab_4)
        self.offsetsListWidget.setObjectName(_fromUtf8("offsetsListWidget"))
        self.gridLayout.addWidget(self.offsetsListWidget, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem20)
        self.writeOffsetsButton = QtGui.QPushButton(self.tab_4)
        self.writeOffsetsButton.setObjectName(_fromUtf8("writeOffsetsButton"))
        self.horizontalLayout_6.addWidget(self.writeOffsetsButton)
        self.gridLayout.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        self.tsTab.addTab(self.tab_4, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.statisticsEdit = QtGui.QPlainTextEdit(self.tab_3)
        self.statisticsEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.statisticsEdit.setReadOnly(True)
        self.statisticsEdit.setObjectName(_fromUtf8("statisticsEdit"))
        self.gridLayout_8.addWidget(self.statisticsEdit, 1, 0, 1, 1)
        self.tsTab.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout_7.addWidget(self.tsTab)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_2 = QtGui.QLabel(self.dockWidgetContents_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_6.addWidget(self.label_2)
        self.offsetEdit = QtGui.QLineEdit(self.dockWidgetContents_5)
        self.offsetEdit.setReadOnly(True)
        self.offsetEdit.setObjectName(_fromUtf8("offsetEdit"))
        self.verticalLayout_6.addWidget(self.offsetEdit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.addOffsetButton = QtGui.QToolButton(self.dockWidgetContents_5)
        self.addOffsetButton.setText(_fromUtf8(""))
        self.addOffsetButton.setObjectName(_fromUtf8("addOffsetButton"))
        self.verticalLayout_3.addWidget(self.addOffsetButton)
        self.deleteOffsetButton = QtGui.QToolButton(self.dockWidgetContents_5)
        self.deleteOffsetButton.setText(_fromUtf8(""))
        self.deleteOffsetButton.setObjectName(_fromUtf8("deleteOffsetButton"))
        self.verticalLayout_3.addWidget(self.deleteOffsetButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.fileDock.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.fileDock)
        self.actionZoom = QtGui.QAction(MainWindow)
        self.actionZoom.setCheckable(True)
        self.actionZoom.setChecked(False)
        self.actionZoom.setObjectName(_fromUtf8("actionZoom"))
        self.actionPan = QtGui.QAction(MainWindow)
        self.actionPan.setCheckable(True)
        self.actionPan.setObjectName(_fromUtf8("actionPan"))
        self.actionFile = QtGui.QAction(MainWindow)
        self.actionFile.setCheckable(True)
        self.actionFile.setChecked(True)
        self.actionFile.setObjectName(_fromUtf8("actionFile"))
        self.actionConsole = QtGui.QAction(MainWindow)
        self.actionConsole.setCheckable(True)
        self.actionConsole.setChecked(True)
        self.actionConsole.setObjectName(_fromUtf8("actionConsole"))
        self.actionDetrendLog = QtGui.QAction(MainWindow)
        self.actionDetrendLog.setCheckable(True)
        self.actionDetrendLog.setChecked(True)
        self.actionDetrendLog.setObjectName(_fromUtf8("actionDetrendLog"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionDate = QtGui.QAction(MainWindow)
        self.actionDate.setObjectName(_fromUtf8("actionDate"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionDefault = QtGui.QAction(MainWindow)
        self.actionDefault.setObjectName(_fromUtf8("actionDefault"))
        self.actionUser = QtGui.QAction(MainWindow)
        self.actionUser.setObjectName(_fromUtf8("actionUser"))
        self.actionAnalysis = QtGui.QAction(MainWindow)
        self.actionAnalysis.setCheckable(True)
        self.actionAnalysis.setChecked(True)
        self.actionAnalysis.setObjectName(_fromUtf8("actionAnalysis"))
        self.actionInterpolation = QtGui.QAction(MainWindow)
        self.actionInterpolation.setObjectName(_fromUtf8("actionInterpolation"))
        self.actionHeader = QtGui.QAction(MainWindow)
        self.actionHeader.setObjectName(_fromUtf8("actionHeader"))
        self.actionDetrend = QtGui.QAction(MainWindow)
        self.actionDetrend.setObjectName(_fromUtf8("actionDetrend"))
        self.actionFigure = QtGui.QAction(MainWindow)
        self.actionFigure.setObjectName(_fromUtf8("actionFigure"))
        self.menuSettings.addAction(self.actionDefault)
        self.menuSettings.addAction(self.actionUser)
        self.menuMenu.addAction(self.actionOpen)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.menuSettings.menuAction())
        self.menuView.addAction(self.actionAnalysis)
        self.menuView.addAction(self.actionConsole)
        self.menuView.addAction(self.actionFile)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionDetrendLog)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionHelp)
        self.menuTools.addAction(self.actionHeader)
        self.menuTools.addAction(self.actionDate)
        self.menuBatch.addAction(self.actionDetrend)
        self.menuBatch.addAction(self.actionFigure)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuBatch.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.tsTab.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionFile, QtCore.SIGNAL(_fromUtf8("triggered(bool)")), self.fileDock.setVisible)
        QtCore.QObject.connect(self.tabWidget, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), self.toolBox.setCurrentIndex)
        QtCore.QObject.connect(self.toolBox, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), self.tabWidget.setCurrentIndex)
        QtCore.QObject.connect(self.actionConsole, QtCore.SIGNAL(_fromUtf8("triggered(bool)")), self.consoleDock.setVisible)
        QtCore.QObject.connect(self.actionAnalysis, QtCore.SIGNAL(_fromUtf8("triggered(bool)")), self.analysisDock.setVisible)
        QtCore.QObject.connect(self.analysisDock, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionAnalysis.setChecked)
        QtCore.QObject.connect(self.consoleDock, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionConsole.setChecked)
        QtCore.QObject.connect(self.fileDock, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionFile.setChecked)
        QtCore.QObject.connect(self.actionOpen, QtCore.SIGNAL(_fromUtf8("triggered()")), self.addFilesButton.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Time Domain Analysis", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Spectral Domain Analysis", None))
        self.analysisDock.setWindowTitle(_translate("MainWindow", "Analysis", None))
        self.label_4.setText(_translate("MainWindow", "Polynomials", None))
        self.label_3.setText(_translate("MainWindow", "Periods", None))
        self.periodEdit.setText(_translate("MainWindow", "0.5 1", None))
        self.periodUnitLabel.setText(_translate("MainWindow", "year", None))
        self.groupBox.setTitle(_translate("MainWindow", "Outliers", None))
        self.label_7.setText(_translate("MainWindow", "Sigma", None))
        self.sigmaEdit.setText(_translate("MainWindow", "30 30 30", None))
        self.sigmaUintLabel.setText(_translate("MainWindow", "(mm)", None))
        self.label_9.setText(_translate("MainWindow", "IQR factor", None))
        self.label_10.setText(_translate("MainWindow", "IQR window", None))
        self.outliersButton.setText(_translate("MainWindow", "Clean", None))
        self.outliersButton.setShortcut(_translate("MainWindow", "Ctrl+C", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Analysis", None))
        self.fitCheck.setText(_translate("MainWindow", "Fit", None))
        self.noOffsetsRadio.setToolTip(_translate("MainWindow", "Offsets have been removed.", None))
        self.noOffsetsRadio.setText(_translate("MainWindow", "Continuous", None))
        self.residualCheck.setText(_translate("MainWindow", "Residuals", None))
        self.detrendButton.setText(_translate("MainWindow", "Detrend", None))
        self.detrendButton.setShortcut(_translate("MainWindow", "Ctrl+D", None))
        self.saveButton.setText(_translate("MainWindow", "Save", None))
        self.saveButton.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Time Domain Analysis", None))
        self.label_11.setText(_translate("MainWindow", "Method", None))
        self.spMethodBox.setItemText(0, _translate("MainWindow", "Lomb-Scargle", None))
        self.label_14.setText(_translate("MainWindow", "Window Type", None))
        self.fftWindowBox.setItemText(0, _translate("MainWindow", "Hamming", None))
        self.label_15.setText(_translate("MainWindow", "Lenght", None))
        self.label_6.setText(_translate("MainWindow", "Data", None))
        self.spDataBox.setItemText(0, _translate("MainWindow", "Originals", None))
        self.spDataBox.setItemText(1, _translate("MainWindow", "Residuals", None))
        self.label_12.setText(_translate("MainWindow", "Log-log fit", None))
        self.spAnalysisButton.setText(_translate("MainWindow", "Spectral Analysis", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Spectral Domain Analysis", None))
        self.consoleDock.setWindowTitle(_translate("MainWindow", "Console", None))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.menuBatch.setTitle(_translate("MainWindow", "Batch", None))
        self.fileDock.setWindowTitle(_translate("MainWindow", "File", None))
        self.label.setText(_translate("MainWindow", "Add Files", None))
        self.addFilesButton.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.filesListWidget.setSortingEnabled(True)
        self.prevButton.setText(_translate("MainWindow", "<", None))
        self.prevButton.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.deleteButton.setText(_translate("MainWindow", "Delete", None))
        self.deleteButton.setShortcut(_translate("MainWindow", "Del", None))
        self.nextButton.setText(_translate("MainWindow", ">", None))
        self.nextButton.setShortcut(_translate("MainWindow", "Ctrl+W", None))
        self.label_5.setText(_translate("MainWindow", "Station", None))
        self.offsetsListWidget.setSortingEnabled(True)
        self.writeOffsetsButton.setText(_translate("MainWindow", "Write", None))
        self.tsTab.setTabText(self.tsTab.indexOf(self.tab_4), _translate("MainWindow", "Offsets", None))
        self.tsTab.setTabText(self.tsTab.indexOf(self.tab_3), _translate("MainWindow", "Statistics", None))
        self.label_2.setText(_translate("MainWindow", "Offsets", None))
        self.actionZoom.setText(_translate("MainWindow", "zoom", None))
        self.actionPan.setText(_translate("MainWindow", "pan", None))
        self.actionFile.setText(_translate("MainWindow", "File Dock", None))
        self.actionConsole.setText(_translate("MainWindow", "Console Dock", None))
        self.actionDetrendLog.setText(_translate("MainWindow", "Show Detrend Log", None))
        self.actionAbout.setText(_translate("MainWindow", "About ", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.actionDate.setText(_translate("MainWindow", "Date Conversion", None))
        self.actionOpen.setText(_translate("MainWindow", "Open File", None))
        self.actionDefault.setText(_translate("MainWindow", "Default", None))
        self.actionUser.setText(_translate("MainWindow", "User", None))
        self.actionAnalysis.setText(_translate("MainWindow", "Analysis Dock", None))
        self.actionInterpolation.setText(_translate("MainWindow", "Data Interpolation", None))
        self.actionHeader.setText(_translate("MainWindow", "Add Header Comments", None))
        self.actionDetrend.setText(_translate("MainWindow", "Detrend", None))
        self.actionFigure.setText(_translate("MainWindow", "Figures", None))

from matplotlibwidget import MatplotlibWidget
