name: Nuitka Build

on:
  push:
    branches: [ main, feature/nuitka-build ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, feature/nuitka-build ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            output_name: app.exe
            icon: TSAnalyzer/resources/images/icon.ico
          - os: macos-latest
            output_name: app
            icon: TSAnalyzer/resources/images/icon.png

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka

    - name: Install macOS dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install ccache
        
    - name: Build with Nuitka
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          python -m nuitka --standalone --follow-imports --include-data-dir=./TSAnalyzer/=TSAnalyzer --windows-disable-console --enable-plugins=pyqt5 --windows-icon-from-ico=${{ matrix.icon }} main.py --output-dir=dist
        else
          python -m nuitka --standalone --follow-imports --include-data-dir=./TSAnalyzer/=TSAnalyzer --macos-create-app-bundle --enable-plugins=pyqt5 --macos-app-icon=${{ matrix.icon }} main.py --output-dir=dist
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-build
        path: |
          dist/main.dist/**
          dist/main.app/**

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: false
        files: |
          dist/main.dist/**
          dist/main.app/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
